// Generated by CoffeeScript 1.10.0
(function() {
  var cp, dotLearn, exec, fs, lessonName, packageJson, path, readme, repo, repoFolder, sourceFolder, targetFolder, templateFolder, unitName;

  cp = require('child_process');

  fs = require('fs-extra');

  exec = require('exec');

  path = require('path');

  repo = process.argv[2];

  lessonName = process.argv[3];

  unitName = process.argv[4] || 'Node Modules';

  sourceFolder = __dirname;

  repoFolder = path.basename(repo, '.git');

  targetFolder = path.join(process.cwd(), repoFolder);

  if (repo.indexOf('-lab') > -1) {
    templateFolder = 'node-lab';
  } else {
    templateFolder = 'node-readme';
  }

  fs.copySync(sourceFolder + "/" + templateFolder, "" + targetFolder);

  dotLearn = fs.readFileSync(targetFolder + "/.learn", {
    encoding: 'utf8'
  });

  dotLearn = dotLearn.replace(/lesson-name/g, lessonName);

  dotLearn = dotLearn.replace(/unit-name/g, unitName);

  fs.writeFileSync(targetFolder + "/.learn", dotLearn);

  readme = fs.readFileSync(targetFolder + "/README.md", {
    encoding: 'utf8'
  });

  readme = readme.replace(/lesson-name/g, lessonName);

  readme = readme.replace(/repo-folder/g, repoFolder);

  fs.writeFileSync(targetFolder + "/README.md", readme);

  if (repo.indexOf('-lab') > -1) {
    packageJson = fs.readJsonSync(targetFolder + "/package.json");
    packageJson.name = repoFolder;
    packageJson.description = lessonName;
    packageJson.repository.url = repo;
    packageJson.bugs.url = repo + "/issues";
    packageJson.homepage = repo + "/#readme";
    fs.writeJsonSync(targetFolder + "/package.json", packageJson);
  }

  console.log(repo, path.basename(repo, '.git'), sourceFolder, targetFolder);

}).call(this);
