
// Generated by CoffeeScript 1.10.0
(function() {
  var exec, fs, path, pwd, repo, shell;

  shell = require('shelljs');

  fs = require('fs-extra');

  exec = require('exec');

  path = require('path');

  repo = process.argv[2];

  console.log(repo, path.basename(repo, '.git'));

  pwd = shell.pwd();

}).call(this);
